
services:
  postgresql:
    image: postgres:17
    container_name: 7OPR_FinalProject_DB
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: FinalProjectDB
    ports:
      - "5432:5432"
    volumes:
        - postgresql_data:/var/lib/postgresql/data
    networks:
      - 7OPR_FinalProject_Network

volumes:
  postgresql_data:

networks:
  7OPR_FinalProject_Network:
    driver: bridge